### ISSUE TITLE
autotrace and tracedigitise enabled causes QGIS to hang

### ISSUE THREAD

**Issue by SteveLowman** [lutraconsulting/qgis-autotrace-plugin#12]
I am working with very large feature sets, which may make a difference. Basically, just having the plug in enabled, and then using some of the Advanced Digitising tools, such as the ‘Split Features’ tool seems to cause the problem, but it doesn’t happen immediately, and I usually get to do a certain amount of digitising before it happens.
The problem certainly can occur without actually using the plugin - it just has to be enabled (I find there is a similar issue with the 'Rectangles Ovals Digitizing' plugin btw). It feels like the processes of digitising may be building up some sort of cache of data that eventually gets too full, but this may just be a subjective impression. Otherwise, it may be an issue of incompatibility with some of those digitising tools.
First it hangs for minute or so before recovering, and then usually the next click you do it hangs indefinitely.
If I manage to disable the plug in after the first hang, then QGIS continues to work normally.

**Comment by saberraz** [comment]
No feedback...and hence closed!
