### ISSUE TITLE
Rubber-band Transparency

### ISSUE THREAD

**Issue by mostlyAtNight** [lutraconsulting/qgis-autotrace-plugin#14]
When I am using the 'regular' add feature tool in QGIS to digitise a polygon feature, I can make the polygon semi transparent so I can see where I am going as I digitise. 

Using the auto trace plug in, I can trace along the boundary of previously created polygons no problem but when I move out into an area where I am digitising 'new' data I sometimes cannot see where I am digitising very easily as the polygon is red and not semi transparent.

Is the a way I can adjust the auto trace polygon to make it semi transparent?

**Comment by saberraz** [comment]
It should be consistent with the color of the digitizing tool in QGIS, e.g. if user changes transparency, rubber-band color...etc, it should be applied to the AT.

**Comment by wonder-sk** [comment]
Fixed in 0edbe599f9cffbc1e3eb5271db82ffabd2dc1236
