### ISSUE TITLE
Duplicating feature when digitizing over areas with islelands

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-autotrace-plugin#18]
When digitizing over polygons containing islelands, AutoTrace creates 2 features.To replicate the problem:

1- Create a new Shape polygon feature
2- Digitize an area
3- Add a Ring
4- Try to use AutoTrace and create a polyon on top of the existing one (which contains a ring)
5- When finished adding the polygon using AT, open the attribute table, it contains another row
![step2](https://cloud.githubusercontent.com/assets/2649047/7372972/c348421c-edc1-11e4-93b6-2ce76dc28a0f.PNG)

![step3](https://cloud.githubusercontent.com/assets/2649047/7373015/fd879ab8-edc1-11e4-9fd4-b46a490332dc.PNG)
![step4](https://cloud.githubusercontent.com/assets/2649047/7373016/fd89f614-edc1-11e4-894d-d4cf3cee357c.PNG)
![step5](https://cloud.githubusercontent.com/assets/2649047/7373017/fd8a8516-edc1-11e4-85c2-96d2001fbcf4.PNG)

**Comment by edspeth** [comment]
Autotrace creates 2 features no matter what you digitise, it's not unique to polygons with islands.
