### ISSUE TITLE
Attribute form does not appear when finished digitsing

### ISSUE THREAD

**Issue by saberraz** [lutraconsulting/qgis-autotrace-plugin#2]
When finished with digitising, the default behavior of QGIS Add Feature tool is to present the end user with the attribute list to fill in. But AutoTrace does not bring up the attribute table.

**Comment by wonder-sk** [comment]
Fixed in 129dde9308a726055316de377dbc7caf15d3bd30

**Comment by tobias47n9e** [comment]
@wonder-sk: Great, thanks!
