### ISSUE TITLE
AutoTrace for QGis 3.x ?

### ISSUE THREAD

**Issue by FloArchaeo** [lutraconsulting/qgis-autotrace-plugin#25]
Hello,

Do you plan to update AutoTrace plugin for QGis 3.x?
Thank you.

**Comment by dwsilk** [comment]
There has been a [Trace digitising tool](https://www.qgis.org/en/site/forusers/visualchangelog214/index.html#feature-trace-digitising-tool) developed by Lutra Consulting in the QGIS core since 2.14.

**Comment by wonder-sk** [comment]
More info here: https://www.lutraconsulting.co.uk/products/autotrace/TraceDigitising/

Since tracing is now a core feature, the plugin will not be updated to QGIS 3.
