### ISSUE TITLE
Drawing polygon is not taken from QGIS options

### ISSUE THREAD

**Issue by tobias47n9e** [lutraconsulting/qgis-autotrace-plugin#9]
QGIS allows to change the appearance of the edit-polygon in order to ease the digitizing of maps with different colours. Autotrace doesn't seem to grab that setting from the options, always using the very bright red and almost non-transparent default. Would it be possible to add that?

**Comment by wonder-sk** [comment]
Fixed in 0edbe599f9cffbc1e3eb5271db82ffabd2dc1236

**Comment by tobias47n9e** [comment]
@wonder-sk: Thank you!
